# Generated by Django 4.2.11 on 2024-04-04 07:01

from django.db import migrations, models
import ipam.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('prefix', ipam.fields.IPNetworkField(help_text='IPv4 or IPv6 network with mask', verbose_name='prefix')),
            ],
            options={
                'verbose_name': 'prefix',
                'verbose_name_plural': 'prefixes',
                'ordering': ('prefix', 'pk'),
            },
        ),
    ]
